/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiMediaWithCropsResponseModel,
  GetMedia20Params,
  GetMediaItemById20Params,
  GetMediaItemByIdParams,
  GetMediaItemByPath20Params,
  GetMediaItemByPathParams,
  GetMediaItemParams,
  GetMediaItems20Params,
  GetMediaParams,
  PagedIApiMediaWithCropsResponseModel
} from '.././schemas/index.js';




  export const getMedia = () => {
/**
 * @deprecated
 */
const getMedia = <TData = AxiosResponse<PagedIApiMediaWithCropsResponseModel>>(
    params?: GetMediaParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/media`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getMedia20 = <TData = AxiosResponse<PagedIApiMediaWithCropsResponseModel>>(
    params?: GetMedia20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/media`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getMediaItem = <TData = AxiosResponse<ApiMediaWithCropsResponseModel[]>>(
    params?: GetMediaItemParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/media/item`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getMediaItemByPath = <TData = AxiosResponse<ApiMediaWithCropsResponseModel>>(
    path: string,
    params?: GetMediaItemByPathParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/media/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getMediaItemByPath20 = <TData = AxiosResponse<ApiMediaWithCropsResponseModel>>(
    path: string,
    params?: GetMediaItemByPath20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/media/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getMediaItemById = <TData = AxiosResponse<ApiMediaWithCropsResponseModel>>(
    id: string,
    params?: GetMediaItemByIdParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/media/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getMediaItemById20 = <TData = AxiosResponse<ApiMediaWithCropsResponseModel>>(
    id: string,
    params?: GetMediaItemById20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/media/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getMediaItems20 = <TData = AxiosResponse<ApiMediaWithCropsResponseModel[]>>(
    params?: GetMediaItems20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/media/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getMedia,getMedia20,getMediaItem,getMediaItemByPath,getMediaItemByPath20,getMediaItemById,getMediaItemById20,getMediaItems20}};
export type GetMediaResult = AxiosResponse<PagedIApiMediaWithCropsResponseModel>
export type GetMedia20Result = AxiosResponse<PagedIApiMediaWithCropsResponseModel>
export type GetMediaItemResult = AxiosResponse<ApiMediaWithCropsResponseModel[]>
export type GetMediaItemByPathResult = AxiosResponse<ApiMediaWithCropsResponseModel>
export type GetMediaItemByPath20Result = AxiosResponse<ApiMediaWithCropsResponseModel>
export type GetMediaItemByIdResult = AxiosResponse<ApiMediaWithCropsResponseModel>
export type GetMediaItemById20Result = AxiosResponse<ApiMediaWithCropsResponseModel>
export type GetMediaItems20Result = AxiosResponse<ApiMediaWithCropsResponseModel[]>
