/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiContentResponseModel,
  GetContent20Params,
  GetContentItemById20Params,
  GetContentItemByIdParams,
  GetContentItemByPath20Params,
  GetContentItemByPathParams,
  GetContentItemParams,
  GetContentItems20Params,
  GetContentParams,
  PagedIApiContentResponseModel
} from '.././schemas/index.js';




  export const getContent = () => {
/**
 * @deprecated
 */
const getContent = <TData = AxiosResponse<PagedIApiContentResponseModel>>(
    params?: GetContentParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/content`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getContent20 = <TData = AxiosResponse<PagedIApiContentResponseModel>>(
    params?: GetContent20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/content`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getContentItem = <TData = AxiosResponse<ApiContentResponseModel[]>>(
    params?: GetContentItemParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/content/item`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getContentItemByPath = <TData = AxiosResponse<ApiContentResponseModel>>(
    path: string,
    params?: GetContentItemByPathParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/content/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getContentItemByPath20 = <TData = AxiosResponse<ApiContentResponseModel>>(
    path: string,
    params?: GetContentItemByPath20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/content/item/${path}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @deprecated
 */
const getContentItemById = <TData = AxiosResponse<ApiContentResponseModel>>(
    id: string,
    params?: GetContentItemByIdParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v1/content/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getContentItemById20 = <TData = AxiosResponse<ApiContentResponseModel>>(
    id: string,
    params?: GetContentItemById20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/content/item/${id}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getContentItems20 = <TData = AxiosResponse<ApiContentResponseModel[]>>(
    params?: GetContentItems20Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/umbraco/delivery/api/v2/content/items`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getContent,getContent20,getContentItem,getContentItemByPath,getContentItemByPath20,getContentItemById,getContentItemById20,getContentItems20}};
export type GetContentResult = AxiosResponse<PagedIApiContentResponseModel>
export type GetContent20Result = AxiosResponse<PagedIApiContentResponseModel>
export type GetContentItemResult = AxiosResponse<ApiContentResponseModel[]>
export type GetContentItemByPathResult = AxiosResponse<ApiContentResponseModel>
export type GetContentItemByPath20Result = AxiosResponse<ApiContentResponseModel>
export type GetContentItemByIdResult = AxiosResponse<ApiContentResponseModel>
export type GetContentItemById20Result = AxiosResponse<ApiContentResponseModel>
export type GetContentItems20Result = AxiosResponse<ApiContentResponseModel[]>
